### ISSUE TITLE
When to send data to the cloud

### ISSUE THREAD

**Issue by eriksven** [COVESA/commercial-vehicles#14]
For the guidelines, I am wondering when which data is actually send from the vehicle to a backend and how much delay we allow between the measurement and the transfer of the sample to a backend. What do you think?

For the curve algorithm, which is used for many data points like the GPS location, I see different options: "slice" the data either with or without overlap and curve or curve after each new sample.

For reference, let us assume the following samples:
![rawSamples](https://github.com/COVESA/commercial-vehicles/assets/44381577/24c32998-4ee1-4af7-9751-bca0bbc8718d)

When we apply the curve algorithm over all data we could get the following result.
![curveApplied](https://github.com/COVESA/commercial-vehicles/assets/44381577/44e643f1-cbab-4174-a9e9-d801156ea3b6)

However, we are dealing with a stream of data and do not have an infinite buffer size to fit all potential samples and also need to make a decision when to send the data to the backend (before infinity).
One approach would be to slice the data set and then apply curve on each slice. We can then send the result per slice directly to the cloud. This would look like this:
![curveSlice](https://github.com/COVESA/commercial-vehicles/assets/44381577/e2d8b8fe-0691-4ee8-9a7f-5ec6d7e841f1)

In this approach, we treat each buffer independently and will always send at least the first and last sample of each slice. A specialization of this would be to let the slices overlap each other so that the last point of one slice is the first point of the next slice. This would like this:
![curveOverlappingSlices](https://github.com/COVESA/commercial-vehicles/assets/44381577/000b5112-7559-4aaf-bc28-ec3dbd225933)

Another approach is to apply curve whenever a new sample gets added to the buffer.  Here we could decide for an each sample whether we keep it and therefore send it to the cloud after curve has been applied for the subsequent sample.
![onlineCurve](https://github.com/COVESA/commercial-vehicles/assets/44381577/652cfd23-b5ce-46d9-97f1-a1b93f08c924)

To avoid that the buffer size becomes too large, we could work with a sliding window and drop the oldest samples from the buffer after pushing it to the cloud.
![onlineCurveEnding](https://github.com/COVESA/commercial-vehicles/assets/44381577/5f505193-ab83-4416-9426-5b7833830b36)

A subsequent question is whether to send the sample always in the moment it is decided that we keep it or to collect a number of samples before sending them. So one could only send the relevent samples every minute etc. or when a local storage is full.

**Comment by tguild** [comment]
Hej @eriksven unless there is separate logic to perform an in-vehicle assessment, the curve sampled data point is considered relevant and should be transmitted back to the cloud. It is a lossy compression algorithm that sends pertinent data based on the error thresholds per signal. The new data point may be actionable and should be sent to the cloud in the relatively near future but can be kept in a buffer and sent as part of a batch.  Note some of our thresholds could potentially be better tuned, we have some default thresholds for temperature and pressure that can studied and improved. 

@yuhanlin-geotab would know better and may want to expound further or correct impressions I have.

**Comment by yuhanlin-geotab** [comment]
Ted is correct. Points output by the curve algorithm should be sent to the
cloud. You may also want to store these points onto some type of persistent
storage on the client, so you can upload them later if the network is down.

Yuhan Lin
Geotab
Embedded Systems Developer

Direct
Toll-free

Visit

(416) 891-2416
+1 (877) 431-8221
www.geotab.com

**Comment by eriksven** [comment]
Thank you for the responses, and I understand that each data point that "survived" the curve sampling should end in the cloud. However, I am not sure what an actual implementation would look like. 

I am wondering when which points go into the curve algorithm. All measured data points get curved at some point in time. But as outlined in my previous comment, I see different approaches like:

- slice the data and apply curve per slice
- have a moving window/buffer of n previous data points (either all measured data points or just the points that were kept in previous runs)

Based on your answer, I assume you would go for a moving window of n previous data where only previously curved points are kept.

The other question is how immediately one needs to send the curved data to the cloud. I see different options depending on what "relatively near future" means for us:

- send each curved data point as soon as it is curved (still resulting in many messages but low end-to-end latency)
- only send data points once n points have been collected
- send curved and kept data points at regular intervals (e.g., every minute)

The second and third option would help to reduce the number of messages sent through the air. Based on your answer, I understand that you would go for the first option since a low latency between the sampling of the data point and arrival in the cloud is one of the requirements of the measurement campaign.

**Comment by yuhanlin-geotab** [comment]
Regarding how the "raw" points get curved, the PositionCurve type serves as
a fixed buffer for points that we want to curve. When the buffer becomes
full, the curve algorithm is run on the buffer, the output points are
collected, and the buffer is (mostly) emptied. We also have other
conditions for running the curve algorithm early.

As for how often we send curved points to the cloud, it depends on your
latency requirements, as you said. For our use case, we actually do option
3. We send all pending curved points to the cloud every 30 seconds.

Yuhan Lin
Geotab
Embedded Systems Developer

Direct
Toll-free

Visit

(416) 891-2416
+1 (877) 431-8221
www.geotab.com
